import React, { useState } from "react";
import {
  FaCheckCircle,
  FaExclamationTriangle,
  FaChevronDown,
  FaChevronUp,
  FaLightbulb,
  FaPenNib,
  FaBriefcase,
} from "react-icons/fa";

const ResumeReport = ({ resumeFeedback }) => {
  const [openSection, setOpenSection] = useState(null);

  if (!resumeFeedback) return null;

  const toggleSection = (section) => {
    setOpenSection(openSection === section ? null : section);
  };

  const Chip = ({ text, color }) => (
    <span
      className={`inline-flex items-center px-4 py-2 rounded-full text-sm font-medium border transition-all duration-300 ${color}`}
    >
      {text}
    </span>
  );

  const Accordion = ({ title, icon, items, id }) => (
    <div className="overflow-hidden rounded-3xl border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-lg transition-colors duration-300">
      <button
        onClick={() => toggleSection(id)}
        className="w-full flex items-center justify-between px-6 py-5 hover:bg-gray-50 dark:hover:bg-slate-700/50 transition-all"
      >
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-2xl bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center">
            {icon}
          </div>

          <span className="text-lg font-semibold text-gray-900 dark:text-white">
            {title}
          </span>
        </div>

        <div className="text-gray-500 dark:text-gray-400">
          {openSection === id ? <FaChevronUp /> : <FaChevronDown />}
        </div>
      </button>

      {openSection === id && (
        <div className="border-t border-gray-200 dark:border-slate-700 px-6 py-5">
          <ul className="space-y-4">
            {items.map((item, index) => (
              <li
                key={index}
                className="flex items-start gap-3 text-gray-700 dark:text-gray-300"
              >
                <FaCheckCircle className="mt-1 text-emerald-500 flex-shrink-0" />

                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );

  return (
    <div className="mt-8 space-y-8">
      {/* AI Summary */}

      <div className="rounded-3xl border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-lg transition-colors duration-300">
        <div className="p-8">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-14 h-14 rounded-2xl bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center">
              <FaLightbulb className="text-2xl text-indigo-600 dark:text-indigo-400" />
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
                AI Resume Summary
              </h2>

              <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                Overall evaluation generated by AI.
              </p>
            </div>
          </div>

          <p className="leading-8 text-gray-700 dark:text-gray-300">
            {resumeFeedback.summary}
          </p>
        </div>
      </div>

      {/* Strengths & Weaknesses */}

      <div className="grid lg:grid-cols-2 gap-6">
        <div className="rounded-3xl border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-lg p-8 transition-colors duration-300">
          <div className="flex items-center gap-3 mb-6">
            <FaCheckCircle className="text-emerald-500 text-xl" />

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
              Strengths
            </h2>
          </div>

          <div className="flex flex-wrap gap-3">
            {resumeFeedback.strengths.map((item, index) => (
              <Chip
                key={index}
                text={item}
                color="bg-emerald-100 dark:bg-emerald-900/30 border-emerald-200 dark:border-emerald-800 text-emerald-700 dark:text-emerald-300"
              />
            ))}
          </div>
        </div>

        <div className="rounded-3xl border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-lg p-8 transition-colors duration-300">
          <div className="flex items-center gap-3 mb-6">
            <FaExclamationTriangle className="text-red-500 text-xl" />

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
              Weaknesses
            </h2>
          </div>

          <div className="flex flex-wrap gap-3">
            {resumeFeedback.weaknesses.map((item, index) => (
              <Chip
                key={index}
                text={item}
                color="bg-red-100 dark:bg-red-900/30 border-red-200 dark:border-red-800 text-red-700 dark:text-red-300"
              />
            ))}
          </div>
        </div>
      </div>

      {/* Missing Sections */}

      <div className="rounded-3xl border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-lg transition-colors duration-300">
        <div className="p-8">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-12 h-12 rounded-2xl bg-yellow-100 dark:bg-yellow-900/30 flex items-center justify-center">
              <FaExclamationTriangle className="text-yellow-600 dark:text-yellow-400" />
            </div>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
              Missing Sections
            </h2>
          </div>

          <div className="grid md:grid-cols-2 gap-4">
            {resumeFeedback.missingSections.map((item, index) => (
              <div
                key={index}
                className="rounded-2xl border border-yellow-200 dark:border-yellow-800 bg-yellow-50 dark:bg-yellow-900/20 px-5 py-4 text-gray-800 dark:text-gray-200"
              >
                {item}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* AI Suggestions */}

      <div className="space-y-5">
        <Accordion
          id="career"
          title="Career Suggestions"
          icon={
            <FaBriefcase className="text-indigo-600 dark:text-indigo-400 text-xl" />
          }
          items={resumeFeedback.careerSuggestions}
        />

        <Accordion
          id="grammar"
          title="Grammar Suggestions"
          icon={
            <FaPenNib className="text-emerald-600 dark:text-emerald-400 text-xl" />
          }
          items={resumeFeedback.grammarSuggestions}
        />

        <Accordion
          id="format"
          title="Formatting Suggestions"
          icon={
            <FaLightbulb className="text-amber-500 dark:text-amber-400 text-xl" />
          }
          items={resumeFeedback.formatSuggestions}
        />
      </div>

      {/* Footer */}

      <div className="rounded-3xl border border-indigo-200 dark:border-indigo-800 bg-gradient-to-r from-indigo-50 via-white to-blue-50 dark:from-slate-800 dark:via-slate-800 dark:to-slate-900 shadow-lg p-6">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-5">
          <div>
            <h3 className="text-xl font-bold text-gray-900 dark:text-white">
              Keep Improving Your Resume 🚀
            </h3>

            <p className="mt-2 text-gray-600 dark:text-gray-400 leading-7">
              Follow the AI recommendations above, improve your ATS score,
              update your resume regularly, and re-analyze it after every major
              change for better job matching.
            </p>
          </div>

          <div className="flex items-center justify-center">
            <div className="w-16 h-16 rounded-2xl bg-indigo-600 text-white flex items-center justify-center shadow-lg">
              <FaLightbulb className="text-3xl" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResumeReport;
